version: '3.3'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: 7XugK4rBzjolP9S
    ports:
      - '5432:5432'
  
  postgres-local:
    image: postgres:13
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgresevent
      POSTGRES_PASSWORD: secure-password
    ports:
      - '5431:5432'

  keycloak:
    image: quay.io/keycloak/keycloak:16.1.1
    environment:
      TZ: America/Sao_Paulo
      JDBC_PARAMS: useSSL=false
      KEYCLOAK_ADMIN: events-hex
      KEYCLOAK_ADMIN_PASSWORD: "%xLdzQI0gjF@J^5587J"
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: secure-password
      DB_PORT: 5432
      KC_HTTP_RELATIVE_PATH: /auth
      # DEBUG: true
      # DEBUG_PORT: '*:8787'
      # KEYCLOAK_LOGLEVEL: DEBUG
      # ROOT_LOGLEVEL: DEBUG
      PROXY_ADDRESS_FORWARDING: 'true'
    ports:
      - '8080:8080'
    depends_on:
      - postgres

  kafka:
    image: bitnami/kafka:latest
    restart: on-failure
    ports:
      - 9092:9092
    environment:
      - KAFKA_CFG_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_NUM_PARTITIONS=3
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - 2181:2181
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka-ui:
    image: provectuslabs/kafka-u
    container_name: kafka-ui
    depends_on:
      - kafka
      - zookeeper
    ports:
      - "8085:8085"
    restart: always
    environment:
      - KAFKA_CLUSTERS_0_NAME=events
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181

  events-event-driven:
    image: gcr.io/global-calling-402520/event-driven-events:latest
    restart: always
    environment:
      - NODE_ENV=production
      - DB_HOST=
      - DB_USER=
      - DB_PASS=
      - DB_NAME=nqcmcuot
      - IDENTITYSERVER_REALM=event-driven
      - IDENTITYSERVER_CLIENT_ID=
      - IDENTITYSERVER_SECRET=
      - IDENTITYSERVER_BASE_URL=
      - JWT_PUBLIC_KEY=
    ports:
      - '3000:3000'
    depends_on:
      - postgres
      - keycloak
